// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB09ds9_KDVoUqTUE0Wyu1N7iS-OrvnjNo',
    appId: '1:236920321372:web:1be9ce43ee8a01b9e6fd99',
    messagingSenderId: '236920321372',
    projectId: 'hedieaty-6a9b0',
    authDomain: 'hedieaty-6a9b0.firebaseapp.com',
    storageBucket: 'hedieaty-6a9b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcRRrKRNExRpafbJ__pPxLYJfZ1rBKGPY',
    appId: '1:236920321372:android:4062ed5d2b3611e4e6fd99',
    messagingSenderId: '236920321372',
    projectId: 'hedieaty-6a9b0',
    storageBucket: 'hedieaty-6a9b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBS4MxZGTgq7TJB1YC9XpjRi4LtupH5EoM',
    appId: '1:236920321372:ios:d14444a08dde5976e6fd99',
    messagingSenderId: '236920321372',
    projectId: 'hedieaty-6a9b0',
    storageBucket: 'hedieaty-6a9b0.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBS4MxZGTgq7TJB1YC9XpjRi4LtupH5EoM',
    appId: '1:236920321372:ios:d14444a08dde5976e6fd99',
    messagingSenderId: '236920321372',
    projectId: 'hedieaty-6a9b0',
    storageBucket: 'hedieaty-6a9b0.firebasestorage.app',
    iosBundleId: 'com.example.hedieaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB09ds9_KDVoUqTUE0Wyu1N7iS-OrvnjNo',
    appId: '1:236920321372:web:e9ce6f46595943e9e6fd99',
    messagingSenderId: '236920321372',
    projectId: 'hedieaty-6a9b0',
    authDomain: 'hedieaty-6a9b0.firebaseapp.com',
    storageBucket: 'hedieaty-6a9b0.firebasestorage.app',
  );

}